### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by nickdesaulniers** [chuckwagoncomputing/fxos-firemote#1]
this repo could use an open source license

**Comment by chuckwagoncomputing** [comment]
Paramikojs uses LGPL, so we should be able to use any license for Firemote, if I understand correctly.
Which should we go with? MPL?

**Comment by nickdesaulniers** [comment]
As long as the modified version of paramiko retains it's LGPL2.1 status (looks like you should add to your forks license the date (year) that you modified it), then it looks like you're free to choose the license for the rest of the work. IANAL.

**Comment by chuckwagoncomputing** [comment]
I added the MPL.
