### ISSUE TITLE
this.setupConnect is not a function

### ISSUE THREAD

**Issue by nickdesaulniers** [chuckwagoncomputing/fxos-firemote#2]
Haven't dug into this yet, but trying things out for the first time, I'm running into this: https://github.com/chuckwagoncomputing/fxos-firemote/blob/8545195825e534693dedaf29fe77842da3ff8082/js/ssh2.js#L29

**Comment by chuckwagoncomputing** [comment]
That's funny. Is it easily reproducible?

**Comment by nickdesaulniers** [comment]
happens for me every time, though I'm trying to connect to a host that doesn't allow password authentication.  Maybe we can catch that error sooner and report it via UX?

**Comment by chuckwagoncomputing** [comment]
Looks like you need to clone paramikojs manually.
cd fxos-firemote/js
git clone https://github.com/chuckwagoncomputing/paramikojs.git

**Comment by nickdesaulniers** [comment]
ah yeah recursively checkout submodules
