### ISSUE TITLE
support for keys

### ISSUE THREAD

**Issue by nickdesaulniers** [chuckwagoncomputing/fxos-firemote#3]
I don't use passwords at all for my ssh hosts, I would consider it bad practice.  We should add the ability to support reading a key from the sd card or indexeddb or generate one.  Maybe porting ssh-keygen with emscripten would help.

**Comment by chuckwagoncomputing** [comment]
paramikojs has support for keys; I removed it so I wouldn't have to try to port everything at once. It should be fairly simple to add back in.

**Comment by nickdesaulniers** [comment]
Nice, can it generate keys?

**Comment by chuckwagoncomputing** [comment]
nope.

**Comment by chuckwagoncomputing** [comment]
Should we use passphrase-encrypted keys?

**Comment by nickdesaulniers** [comment]
It would be good to assume the keys may or may not have passphrases.

**Comment by chuckwagoncomputing** [comment]
But if we're creating our own keys?

**Comment by nickdesaulniers** [comment]
Oh, let's worry about supporting keys made elsewhere first, before trying to tackle key gen.  I don't use passphrases but I'm not sure if that's considered bad practice.

**Comment by chuckwagoncomputing** [comment]
I have disobeyed you. Keygen is working. (no passphrase)
Now for a way to export the public key. Any ideas?
(I have a couple bad ones/ones that won't work.)

**Comment by nickdesaulniers** [comment]
I am not a sysadmin, but what I do is allow for password authentication while my server is disconnected from the WAN and is only available locally.  I then SCP my keys up to the box.  Then I disable password authentication and verify that publickey auth is working.  Then I connect my box back to the WAN.  Is there a better way?  I hope so, but this is something that you set up once and forget.  I've only had to do it maybe 4 times in 4 years.

**Comment by chuckwagoncomputing** [comment]
Support for keys added.
