### ISSUE TITLE
Scale trouble on fxos/B2G 2.+

### ISSUE THREAD

**Issue by fabbox** [chuckwagoncomputing/fxos-firemote#4]
Hello, 
very nice project !

I've got to issue so I'll open two issues. They are unrelated. 

When I start the app, the main page appears very tiny (fonts, icons, bar). I wonder if you could you add `<meta name="viewport" content="width=device-width">` in the header of index.html to prevent my "tiny" page trouble ?

**Comment by chuckwagoncomputing** [comment]
Re-open this if it's not fixed. I couldn't reproduce it.
