### ISSUE TITLE
Canot select server

### ISSUE THREAD

**Issue by eliemichel** [chuckwagoncomputing/fxos-firemote#7]
I just installed the application and added a new server.
When I tap on the server name, I get the following error:

```
TypeError: this.setupConnect is not a function
```

and nothing hapens.

**Comment by chuckwagoncomputing** [comment]
https://github.com/chuckwagoncomputing/fxos-firemote/issues/2

TL;DR You need to clone paramikojs manually
cd fxos-firemote/js
git clone https://github.com/chuckwagoncomputing/paramikojs.git

If you're running FXOS 2.1+, don't even bother trying it; there's a fatal bug in TCPSockets.
https://bugzilla.mozilla.org/show_bug.cgi?id=1117182
Feel free to add yourself to the CC list..

**Comment by eliemichel** [comment]
Crap, this bug sucks…

PS: Maybe a line in the readme about paramikojs could be a plus!
